name: Power_Pipeline

on:
  push:

jobs: 
 Docker_Image:
    runs-on: ubuntu-latest
    #needs: ["JFrog"]
    steps:    
        - name: Checkout code
          uses: actions/checkout@master
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: "{{defaultContext}}:mysubdir"
            push: true
            tags: user/app:latest
