name: Power_Pipeline

on:
  push:

jobs: 
 Docker_Image:
    runs-on: ubuntu-latest
    #needs: ["JFrog"]
    steps:    
        - name: Checkout code
          uses: actions/checkout@master

        - name: Set up AWS CLI
          run: |
           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
          env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

          
        - name: check files
          run: |
               docker-compose --version
               ls -l
               aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 637423247927.dkr.ecr.ap-south-1.amazonaws.com
               docker --version
               docker build -t powerpipeline .
               docker tag powerpipeline:latest  609695713455.dkr.ecr.ap-southeast-1.amazonaws.com/powerpipeline:latest
          
               # push the image into aws ecr

               docker push 637423247927.dkr.ecr.ap-south-1.amazonaws.com/powerpipeline:latest

                env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
